str1 = input("Enter string 1:")
str2 = input("Enter string 2:")
a = str1+str2
print("Upper Function:",a.upper())
print("Lower Function:",a.lower())
print("Title Function:", a.title())
print("Swapcase Function:", a.swapcase())
print("Capitalize Function:", a.capitalize())
print("Casefold Function:", a.casefold())
print("Center Function (width 30):", a.center(30))
print("Count of 'a':", a.count('a'))
print("Starts with 'hel':",a.startswith("hel"))
print("Endswith 'ing':", a.endswith('ing'))
print("Find 'a':", a.find('a'))
print("Is Alnum:", a.isalnum())
print("Is Digit:", a.isdigit())
print("Is Numeric:", a.isnumeric())
print("Is Space:", a.isspace())
print("Replace 'a' with 'X':", a.replace('a', 'X'))
print("Join Function:",str1.join(str2))
b = "name\nclass\nmarks"
print("Split Lines:",b.splitlines())
print("Translate Function:",a.maketrans(str1,str2))